#!/usr/bin/env python3
"""
easyinstaller - Build cross-platform installers for Python applications
"""

import argparse
import os
import sys
import json
import shutil
import subprocess
from pathlib import Path
from datetime import datetime

try:
    from ruamel.yaml import YAML
except ImportError:
    print("ERROR: ruamel.yaml not installed. Run: pip install ruamel.yaml")
    sys.exit(1)


class EasyInstallerBuilder:
    def __init__(self, config_file, output_dir="build"):
        self.config_file = Path(config_file)
        self.output_dir = Path(output_dir)
        self.build_timestamp = datetime.now().isoformat()
        self.config = {}
        
    def load_config(self):
        """Load configuration from YAML file"""
        if not self.config_file.exists():
            raise FileNotFoundError(f"Config file not found: {self.config_file}")
        
        yaml = YAML()
        with open(self.config_file) as f:
            self.config = yaml.load(f)
        
        print(f"✓ Loaded config: {self.config.get('project_name', 'Unknown')}")
        return self.config
    
    def validate_config(self):
        """Validate required config fields"""
        required_fields = ['project_name', 'project_version', 'platforms']
        for field in required_fields:
            if field not in self.config:
                raise ValueError(f"Missing required config field: {field}")
        print("✓ Configuration valid")
    
    def create_build_dirs(self):
        """Create output directory structure"""
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        for platform in self.config.get('platforms', []):
            platform_dir = self.output_dir / platform
            platform_dir.mkdir(parents=True, exist_ok=True)
        
        print(f"✓ Created build directories in {self.output_dir}")
    
    def copy_files(self, source_base="."):
        """Copy files as specified in config"""
        copy_files = self.config.get('copy_files', [])
        
        for item in copy_files:
            src = Path(source_base) / item.get('from', '')
            dest_rel = item.get('to', '')
            
            if src.exists():
                for platform_dir in self.output_dir.iterdir():
                    if platform_dir.is_dir():
                        dest = platform_dir / dest_rel
                        dest.parent.mkdir(parents=True, exist_ok=True)
                        if src.is_file():
                            shutil.copy2(src, dest)
                        elif src.is_dir():
                            if dest.exists():
                                shutil.rmtree(dest)
                            shutil.copytree(src, dest)
                        print(f"  ✓ Copied {item['from']} → {platform_dir.name}/")
        
        print("✓ File copy complete")
    
    def generate_windows_installer(self):
        """Generate Windows installer using NSIS template"""
        nsis_template = self.config.get('windows', {})
        nsis_dir = self.output_dir / 'windows'
        
        # Create installer.nsi from template
        project_name = self.config['project_name']
        project_version = self.config['project_version']
        start_file = nsis_template.get('start_file', 'app.exe')
        install_dir = nsis_template.get('default_install_dir', r'C:\Program Files\MyApp')
        
        nsi_content = f"""
; easyinstaller - Generated by build.py
; Project: {project_name} v{project_version}

!include "MUI2.nsh"

Name "{project_name}"
OutFile "{project_name}-{project_version}-installer.exe"
InstallDir "{install_dir}"

!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"
  File /r "*.*"
  CreateShortcut "$SMPROGRAMS\\{project_name}.lnk" "$INSTDIR\\{start_file}"
SectionEnd

Section "Uninstall"
  RMDir /r "$INSTDIR"
  Delete "$SMPROGRAMS\\{project_name}.lnk"
SectionEnd
"""
        
        nsi_file = nsis_dir / "installer.nsi"
        with open(nsi_file, 'w') as f:
            f.write(nsi_content)
        
        print(f"✓ Generated NSIS template: {nsi_file}")
        print(f"  (To build .exe, install NSIS and run: makensis installer.nsi)")
    
    def generate_linux_installer(self):
        """Generate Linux installer script"""
        linux_config = self.config.get('linux', {})
        linux_dir = self.output_dir / 'linux'
        
        project_name_lower = self.config['project_name'].lower()
        project_name = self.config['project_name']
        project_version = self.config['project_version']
        start_file = linux_config.get('start_file', 'app.sh')
        
        installer_script = f"""#!/bin/bash
# {project_name} Installer
# Version: {project_version}

set -e

INSTALL_DIR="${{HOME}}/.local/{project_name_lower}"

echo "Installing {project_name} to $INSTALL_DIR..."

mkdir -p "$INSTALL_DIR"
cp -r ./* "$INSTALL_DIR/"

# Create launcher script
cat > ~/.local/bin/{project_name_lower} << 'EOF'
#!/bin/bash
cd "$INSTALL_DIR"
exec ./{start_file} "$@"
EOF

chmod +x ~/.local/bin/{project_name_lower}

echo "✓ Installation complete!"
echo "Run: {project_name_lower}"
"""
        
        installer_file = linux_dir / "install.sh"
        with open(installer_file, 'w') as f:
            f.write(installer_script)
        os.chmod(installer_file, 0o755)
        
        print(f"✓ Generated Linux installer: {installer_file}")
    
    def generate_macos_installer(self):
        """Generate macOS installer package"""
        mac_config = self.config.get('mac', {})
        mac_dir = self.output_dir / 'mac'
        
        project_name = self.config['project_name']
        project_version = self.config['project_version']
        start_file = mac_config.get('start_file', 'app.sh')
        
        installer_script = f"""#!/bin/bash
# {project_name} Installer (macOS)
# Version: {project_version}

set -e

INSTALL_DIR="/Applications/{project_name}"

echo "Installing {project_name} to $INSTALL_DIR..."

sudo mkdir -p "$INSTALL_DIR"
sudo cp -r ./* "$INSTALL_DIR/"

echo "✓ Installation complete!"
echo "Run: open /Applications/{project_name}/{start_file}"
"""
        
        installer_file = mac_dir / "install.sh"
        with open(installer_file, 'w') as f:
            f.write(installer_script)
        os.chmod(installer_file, 0o755)
        
        print(f"✓ Generated macOS installer: {installer_file}")
    
    def generate_build_info(self):
        """Create build metadata file"""
        build_info = {
            'project_name': self.config.get('project_name'),
            'project_version': self.config.get('project_version'),
            'project_author': self.config.get('project_author'),
            'project_website': self.config.get('project_website'),
            'platforms': self.config.get('platforms', []),
            'build_timestamp': self.build_timestamp,
        }
        
        info_file = self.output_dir / "BUILD_INFO.json"
        with open(info_file, 'w') as f:
            json.dump(build_info, f, indent=2)
        
        print(f"✓ Created build metadata: {info_file}")
    
    def build(self):
        """Execute full build process"""
        try:
            print("\n" + "="*60)
            print(f"easyinstaller - Building {self.config_file.name}")
            print("="*60 + "\n")
            
            self.load_config()
            self.validate_config()
            self.create_build_dirs()
            self.copy_files()
            
            # Generate platform-specific installers
            for platform in self.config.get('platforms', []):
                if platform == 'windows':
                    self.generate_windows_installer()
                elif platform == 'linux':
                    self.generate_linux_installer()
                elif platform == 'mac':
                    self.generate_macos_installer()
            
            self.generate_build_info()
            
            print("\n" + "="*60)
            print(f"✓ Build successful! Output: {self.output_dir.absolute()}")
            print("="*60 + "\n")
            
            return True
            
        except Exception as e:
            print(f"\n✗ Build failed: {e}", file=sys.stderr)
            return False


def main():
    parser = argparse.ArgumentParser(
        description='easyinstaller - Build cross-platform installers for Python applications'
    )
    parser.add_argument(
        '--config',
        required=True,
        help='Path to configuration YAML file (required)'
    )
    parser.add_argument(
        '--output',
        default='build',
        help='Output directory for built installers (default: build)'
    )
    
    args = parser.parse_args()
    
    builder = EasyInstallerBuilder(args.config, args.output)
    success = builder.build()
    
    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
